### ISSUE TITLE
tree_to_seq branch

### ISSUE THREAD

**Issue by molsim** [edraizen/HistoneDB#100]
I added the functionality to click on items in the tree and get redirected to the sequence page.
I do not know how to activate the correct row in the table though.
Do you have an idea what JS code to place in sequences.html?
see             //TODO: How to activate and scroll to correct row???

**Comment by edraizen** [comment]
I would start by showing all records in the table and then: 
$table.bootstrapTable('scrollTo', number_of_row);

**Comment by edraizen** [comment]
Another option would be adding it to extra_seq_params, and would only show the one sequence in the table

**Comment by edraizen** [comment]
http://bootstrap-table.wenzhixin.net.cn/documentation/
