### ISSUE TITLE
Multiple variants and H2A.X/Z

### ISSUE THREAD

**Issue by molsim** [edraizen/HistoneDB#101]
After trying to fix H2As - two suggestions:
1) Add variant assignment by SQEF motif search and override hmm if found.
2) allow multiple variants point to one sequence for curated.
Is this feasible?

**Comment by edraizen** [comment]
Have you compared the scores for sequences that exhibit both? I think that H2A.X comes up as above the threshold, but not classified.

If we used the presence of the H2A.X motif I think we would have rethink our whole classification algorithm. Also, the HMM is doing this already to an extent. I'll look soon.

**Comment by edraizen** [comment]
Here is the logo of the H2A.X HMM. The H2A.X does have the most information content.

![9c329f10-4c17-11e5-8dff-f719cf72a94a](https://cloud.githubusercontent.com/assets/5691412/9500945/544ec06e-4bf6-11e5-861b-99fc1f223dcc.png)

**Comment by edraizen** [comment]
Ok, so one problem when adding the regex, we only have one sequence from canonicalH2A:

```python
In [1]: Sequence.objects.filter(variant="canonicalH2A", sequence__regex="SQ[ED][YFLI]$")
Out[1]:
[<Sequence: >398366187|saccharomyces|canonicalH2A
MSGGKGGKAGSAAKASQSRSAKAGLTFPVGRVHRLLRRGNYAQRIGSGAPVYLTAVLEYL
AAEILELAGNAARDNKKTRIIPRHLQLAIRNDDELNKLLGNVTIAQGGVLPNIHQNLLPK
KSAKATKASQEL
>]

**Comment by molsim** [comment]
also this one 19115333	H2A.X	Schizosaccharomyces pombe 972h-
should show up.
But this is in curated set - the NR would pull much more

**Comment by edraizen** [comment]
Well that one comes up as H2A.X already!

**Comment by edraizen** [comment]
I fixed the filter so it should work and I have updated the score models to allow for the regex classification. Should I close the issue?
