### ISSUE TITLE
Thresholds and plant H2As

### ISSUE THREAD

**Issue by molsim** [edraizen/HistoneDB#103]
We need to do smith with thresholds.
Currently plant H2As do not pass them.
Eg. gi|673921668|ref|NP_001288376.1|
even it is a curated one!

**Comment by anna-panchenko** [comment]
We will never be able to get 100% coverage with high specificity so it is expected that "some" (not many though) sequences will be missed. I would rather provide less coverage than false positives. So far I did not see false positives but will keep looking.

**Comment by molsim** [comment]
The problem currently is our own curated sequences for plant H2As are not passing these thresholds.
And we are not getting other plants also.

**Comment by anna-panchenko** [comment]
I cannot find this sequence on our website.
