### ISSUE TITLE
do we load full seqs in DB?

### ISSUE THREAD

**Issue by molsim** [edraizen/HistoneDB#104]
Do we load full seq in DB from HMM results?
I guess only the matching domains are there not the full seqs.
SQEF motifs at the end get lost

**Comment by edraizen** [comment]
We just load the domains; it would would be easy to get the correct sequence though

**Comment by molsim** [comment]
How to do it effectively? We will need to search nr 100 000 times?

**Comment by edraizen** [comment]
Maybe using Bio.SeqIO.index_db() or blastdbcmds?

**Comment by edraizen** [comment]
I am working on this now using blastdbcmd

**Comment by molsim** [comment]
Great!
