### ISSUE TITLE
score regex

### ISSUE THREAD

**Issue by molsim** [edraizen/HistoneDB#106]
In buildvariants.py
shouldn't this line
            new_score, created = Score.objects.get_or_create(variant__id="H2A.X")
be changed to smith like this
            new_score, created = Score.objects.get_or_create(sequence=s,variant__id="H2A.X")
            s.variant_id=H2A.X
           s.save()

**Comment by edraizen** [comment]
Yes, that seems right. I didn't do much testing because it only found one sequence.

**Comment by molsim** [comment]
I guess that's because SQEF motifs are striped?  Otherwise should be plenty H2A.X in nr.
