### ISSUE TITLE
New feature for H1

### ISSUE THREAD

**Issue by anna-panchenko** [edraizen/HistoneDB#108]
please add new feature:
region, PDB 1hst (residues #107 97-end)
name: "AKP helix"
source: CDD database
Description: positively charged carboxy- terminal domain involved in specific protein-protein and protein-DNA interactions, possibly plays role in suppressing core histone tail domain acetylation in chromatin fiber.

**Comment by edraizen** [comment]
Is this for all H1 or just H1.0?

**Comment by anna-panchenko** [comment]
I think for all H1

Sent from my iPhone

On Aug 27, 2015, at 8:52 PM, edraizen <notifications@github.com<mailto:notifications@github.com>> wrote:


Is this for all H1 or just H1.0?
