### ISSUE TITLE
Analyze sequences

### ISSUE THREAD

**Issue by anna-panchenko** [edraizen/HistoneDB#110]
I submitted a sequence of H1 and returned: "Most likely unknown" - not clear what it means.
Blast p-values were very low with other H1-sequences from the database so why "unknown"?
We should sort the hits with respect to p-values.

**Comment by edraizen** [comment]
Can you give me an example sequence?

**Comment by anna-panchenko** [comment]
gi|285815414|tpg|DAA11306.1|

**Comment by edraizen** [comment]
This seems to be because the HMM score does not meet the threshold. I have added the option to view the analyzed sequence with the blast results to see what happened with the classification.
