### ISSUE TITLE
GenBank description

### ISSUE THREAD

**Issue by anna-panchenko** [edraizen/HistoneDB#115]
"Automatically extracted sequence" table, GenBank descriptions should probably come from "Definition" field, like for GI 24475863:
histone H1oo isoform 1 [Homo sapiens]

Currently we say for this GI:
"CURATED SEQUENCE: Homo|24475863|OO_H1.8 Homo_OO_H1.8_24475863"

"Curated sequence" is not a part of GenBank description, this is our annotation, correct?

**Comment by molsim** [comment]
Yes, curated sequences are special. They show up in automatically extracted set, but we replace their description.
I think that with 100 000 sequences discrepancies in definition will be hard to notice.

**Comment by molsim** [comment]
fixed
