### ISSUE TITLE
Search in table problem

### ISSUE THREAD

**Issue by molsim** [edraizen/HistoneDB#126]
We have some problems with search in table via the embedded field:
1) Fist of all, if it does not find something it does not say "No matches", it says "Loading, please, wait"
2) The search code in search.py returns internal errors, in this code, which are not caught by except.
There are multiple old style variants.
Now if I fix it, the search becomes very slow.

        try:
            variant = OldStyleVariant.objects.get(name__icontains=search_text.replace(" ", "_")).updated_variant
            
            if self.navbar:
                self.redirect = redirect(variant)
            else:
                self.query.format("variant_id", "is", variant.id, str)
            return
        except OldStyleVariant.DoesNotExist: #   changed by Alexey 9/11/2015
        # except:
            pass

**Comment by edraizen** [comment]
Maybe the "__icontains" is slowing it down? I recently changed that to allow the new variant names with underscores.

**Comment by molsim** [comment]
Point 1 - fixed - simply javascript error in MSA when no sequences found.
will check icontains now

**Comment by molsim** [comment]
Still a mystery for me, which JS function handles the quick search in table?

**Comment by molsim** [comment]
Ok, fixed it by not allowing search with one symbol.
