### ISSUE TITLE
curated sequences for cenH3

### ISSUE THREAD

**Issue by anna-panchenko** [edraizen/HistoneDB#128]
If I choose cenH3 variants from Giillardia, Phytophtora or Plasmodium, they are not aligned to canonical from the same organisms.

**Comment by molsim** [comment]
Giillardia, and Plasmodium fixed, Phytophtora no good canonical sequence in genbank

**Comment by molsim** [comment]
I made a fix to display homo by default, and only one sequence if the canonical is not found.
also added H3.3 in look up. (yeast canonical is H3.3)
