### ISSUE TITLE
features

### ISSUE THREAD

**Issue by anna-panchenko** [edraizen/HistoneDB#129]
Features of type "Characteristic T->X substitution" - does it refer to the substitution of T in canonical into X in the variant? If yes, it should be specified in the description. Also, I would use one-letter code for the feature name so it is clear on the display.

**Comment by molsim** [comment]
I clarified the description.
One letter would be less understandable, which one then? we might have 2 -3 substitutions, so will need several letters.

**Comment by anna-panchenko** [comment]
For each feature we could have several letters, for example, if it is T->X, we could say "T"... Although, since we don't have labels/features listed below each alignment, the more descriptive features might be more useful. It is upto you, but when i looked at this example, feature labels were overlapping.

**Comment by molsim** [comment]
Yes, I'd say both solutions are not ideal. I'll keep it as is for now.
Anyway, changing the labels is easy - they all are in features.json file.
