### ISSUE TITLE
Keys

### ISSUE THREAD

**Issue by anna-panchenko** [edraizen/HistoneDB#131]
Keys are not well defined, i don't think they correspond to exactly 80% ientical or 50% identical columns:
Keys: red - 80% identical, blue - 50% identical columns. X-denotes ambiguous positions in consensus sequence

there are also blue columns with "X" in consensus sequence?

**Comment by molsim** [comment]
I would need an example to check.
Technically: two A and two L in an alignment of 4 sequence will give you that.
50% conservation, but you do not know whether to put A or L into consensus.

**Comment by anna-panchenko** [comment]
how would you color columns which are more than 80% identical?

**Comment by molsim** [comment]
they will be red. if we have X in the consensus - this means that the identity can not be more than 50 %.
However, it can be roughly 50% - then we have it colored in blue.
