### ISSUE TITLE
add user sequence comparison view, reviewer 1

### ISSUE THREAD

**Issue by molsim** [edraizen/HistoneDB#148]
When a query histone sequence is compared to the sequences stored in the database ('Analyze Your Sequence' tab) one of the results is a graphical representation of the alignment of the similar sequences found in the database. However, the query sequence is not included in this representation, which hinders the comparison.

**Comment by edraizen** [comment]
The query sequence **is** the sequence aligned to the selected blast hit -- Not the canonical like it is on the other pages. I've made this clear by changing the name to QUERY. 

(1) Is this sufficient? 

(2) I can show the query sequence as a separate view -- a single sequence in pViz using the features from the HMM classifier only. I can also make the Quick MSA align the selected sequence to the canonical to be consistent with with other pages.

(3) I can also make the quick MSA show three sequences: the query, the canonical, and the blast hit.

Which do you think would be best?

**Comment by molsim** [comment]
I think what we have now is pretty sufficiency.
Great job!
