### ISSUE TITLE
modify blast hist table, reviewer 2

### ISSUE THREAD

**Issue by molsim** [edraizen/HistoneDB#151]
4) "Table lists similar sequences from the HistoneDB database containing curated and automatically extracted histone sequences" It could be useful at that point an extra column in the table indicating whether the sequence is curated or automatically retrieved.

**Comment by edraizen** [comment]
I re-added the description column, which says if its curated or not. However, would it be better just to have a boolean column so it fits on one line?

**Comment by dlandsman** [comment]
Hi
How do I get access to this version? To see what you have done?
Thanks
David

=====================================
David Landsman, Ph.D.
Chief, Computational Biology Branch
 NCBI, NLM, NIH
Bethesda, Maryland, U.S.A.
=====================================

**Comment by edraizen** [comment]
Go to http://mwebdev2.ncbi.nlm.nih.gov/projects/HistoneDB2.0/

**Comment by molsim** [comment]
I can not see this new column. Could you, please, recheck it?
