### ISSUE TITLE
canonical variant nameing (underscore or no underscore)

### ISSUE THREAD

**Issue by edraizen** [edraizen/HistoneDB#155]
Currently, many of the scripts are broken because I used names like "canonicalH2A", but many have names like "canonical_H2A" (with the underscore). All of the canonical pages look for sequences with names that do not include the underscore.

**Comment by molsim** [comment]
I'll try to look into it. Do you remember when this problem appeared?

**Comment by molsim** [comment]
Basically, I reversed several lines of code here 9c3da9d3b99403077ddd6b834ad153a7acf872f1
to make canonical pages work again.
However, I'm not 100% sure what was the reason for adding them before?
