### ISSUE TITLE
Add option to build nucleosome

### ISSUE THREAD

**Issue by edraizen** [edraizen/HistoneDB#26]
Tasks:
- Create toolbar "Nucleosome Builder" which opens a modal, with 8 boxes, 2 for each histone, if no variants are added, use cononical histones
- Run Alexey's script
- Open pv (protein veiwer) and have option to download
- Add option "Add to nucleosome" to menu "View/Download selected"
- Opens Nucleosome Builder and adds selected in to corect histone box

**Comment by molsim** [comment]
I keep it in mind. But after we submit the paper.
