### ISSUE TITLE
Browser gets unresponsive

### ISSUE THREAD

**Issue by molsim** [edraizen/HistoneDB#41]
For waterer reason after clicking several times on histone links on main page and going back,
browser hangs. 100% CPU usage.
Tested with Chrome.
Safari sometimes takes too long to load.
Apparently some problems with javascript trees.

**Comment by anna-panchenko** [comment]
The same thing happened to me too.

**Comment by neksa** [comment]
Confirm this bug on Safari.
In particular H3 hangs it every time I try to open it.
http://www.ncbi.nlm.nih.gov/projects/histonedb/index.fcgi/type/H3/

Tried to debug it, the last thing I see before it hangs is a series of ajax network requests. It could be also infinite event loop trying to load the data.

**Comment by molsim** [comment]
Yep, this is a serious issue, I can not view the H3 page.
On the other hand I could do it a couple of days ago.

**Comment by edraizen** [comment]
I think I fixed this: please see the dev server. I will push to test and production soon!

**Comment by edraizen** [comment]
Ok, this is now fixed in the production site
