### ISSUE TITLE
Advance filter

### ISSUE THREAD

**Issue by anna-panchenko** [edraizen/HistoneDB#43]
Some Advance filter options are misspelled for "All sequences" tab: ex "insesitive".
what does it mean "in (comma separated)?

"Only show unique sequences where no organism has multiple sequenes that are identical" - sequences is misspelled

**Comment by edraizen** [comment]
I'll fix those typos, thank!  "in (comma separated)" means it can be in a list of items, which are separated by a comma. E.g. to get sequences from H2A.B and H2A.X, type in "H2A.B,H2A.X", with the menu item "in (comma separated)" selected. Does that make sense?
