### ISSUE TITLE
"All sequences" tab

### ISSUE THREAD

**Issue by anna-panchenko** [edraizen/HistoneDB#44]
"previous name in NR" - why previous? should not it be "GenBank defline"?

**Comment by edraizen** [comment]
This field came from the description in FASTA header from the NR database. I chose the title "Previous" because many of descriptions may be incorrect, and the new variant annotation should be the new name. What would be the best way to phrase that?

**Comment by anna-panchenko** [comment]
I suggest “Current GenBank description”
