### ISSUE TITLE
Advanced filter

### ISSUE THREAD

**Issue by anna-panchenko** [edraizen/HistoneDB#45]
I went to "All sequences" tab for H1 and use advanced filter.. the pull-down menu for "histone" has two H1 and other core histones (should be variants for H1). So if I choose H2A, it shows H2A variants in this table although the page title says H1 histone.

**Comment by edraizen** [comment]
I can do two things here:

1) Only allow to search H1 and it's variants, removing all of the options for other variants
2) Allow anything to be searched, but if it is not an "H1" redirect to the main search page on submit.

Which do you think would be best?

**Comment by anna-panchenko** [comment]
I suggest using option 1)
