### ISSUE TITLE
No H1.0 for primates

### ISSUE THREAD

**Issue by molsim** [edraizen/HistoneDB#52]
When trying H1->H1.0 zoom to primates via sunburst->click on "View seas with this taxa" returns no results
IS H1.0 in fact a CanonicalH1 - can we ask Paul Talbert?

**Comment by edraizen** [comment]
When I go H1->H1.0->Primates, I get lots of sequences. Are you still having this probelm?

As with H1.0, I'm not sure. Hopefully Paul will get back to us.

**Comment by edraizen** [comment]
I think H1.0, is its own variant: "H1.0 (H1°) is an animal-specific clade, including avian H5."

**Comment by edraizen** [comment]
We resolved this, so I am closing it. Feel free to reopen it it.
