### ISSUE TITLE
a lot of Ubiquitine ligases in canonicalH1

### ISSUE THREAD

**Issue by molsim** [edraizen/HistoneDB#54]
Check GI 817255336
or cacnonical H1 for primates.
RefSeq PREDICTED - a lot of E3 unbiquitin ligases ???
Why??? Our problem or RefSeq problem?

**Comment by edraizen** [comment]
So now we only have one Ubiquitin ligase in H1.0 from Wickerhamomyces ciferrii with gi 754402344 and HMM score of 67.1. That score is near the threshold (~66), so maybe we should increase the threshold?

**Comment by leonardomarino** [comment]
Yes, let's increase the threshold 

--
Leonardo Mariño-Ramírez
marino@marino-johnson.org

---- edraizen wrote ----
