### ISSUE TITLE
sequence logo

### ISSUE THREAD

**Issue by anna-panchenko** [edraizen/HistoneDB#55]
In some alignments there are "X" in consensus sequence in all gapped columns.

**Comment by edraizen** [comment]
Yes, this is because it takes too much time to load in the entire seed sequence, so I only read in the first 100. I will pre-calculate the consensus sequnces to make sure there are no X's.

**Comment by edraizen** [comment]
We are removing the old histone db seed sequences, which were too large to display so Xs were added.
