### ISSUE TITLE
Suggested bug fix

### ISSUE THREAD

**Issue by molsim** [edraizen/HistoneDB#57]
in djangophilocore/management/commands/buildtaxonomytoc.py

Replace
from server.phylocore_models import *
with
from djangophylocore.models import *

It is unclear what server.phylocore_models refers too, and throws an error during
python manage.py buildtaxonomytoc

**Comment by edraizen** [comment]
Oh nice catch, I forgot to change that when I separated the projects. If
you already changed it, do you want to start a pull request?

**Comment by molsim** [comment]
I fixed it on the master. My version is too messy now.
