### ISSUE TITLE
suggested modification

### ISSUE THREAD

**Issue by molsim** [edraizen/HistoneDB#58]
Some paths in settings.py are machine specific.
Can we do this change:

 \# STATIC_URL = '/projects/histonedb/HistoneDB/static/'
STATIC_URL=os.path.join(BASE_DIR, "static/")

 \# STATIC_ROOT = '/web/public/htdocs/projects/histonedb/HistoneDB/static/'
STATIC_ROOT=os.path.join(BASE_DIR, "static/")

**Comment by edraizen** [comment]
Hmm, we need to distinguish between the two paths. ROOT is how to access the files on the filesystem and URL is how to access the files through the web. I can add the URL as a environment variable.

**Comment by molsim** [comment]
The problem is that:
with older version of static url - some of the initial manage.py scripts fail on my laptop.
While with the suggested version there is a clash with 
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
and web server complains 
ImproperlyConfigured: The STATICFILES_DIRS setting should not contain the STATIC_ROOT setting

**Comment by edraizen** [comment]
STATIC_ROOT is not needed becuase we don't need to collect static. We will use STATIC_ROOT_AUX in scripts who need access to the path.
