### ISSUE TITLE
View sequences from the taxonomy tab

### ISSUE THREAD

**Issue by leonardomarino** [edraizen/HistoneDB#60]
![screen shot 2015-08-03 at 12 30 47 pm](https://cloud.githubusercontent.com/assets/7528337/9042249/81e1cbca-39db-11e5-8e88-4d44cecff22d.png)

When browsing the Variant: macroH2A I am unable to display sequences within the taxonomy tab. Please see the screenshot and the "View macroH2A sequences within this taxa" button does not display sequences.

**Comment by edraizen** [comment]
This is fixed on the dev server, will promote to live soon!

**Comment by molsim** [comment]
Not working again.

**Comment by edraizen** [comment]
This happened when I added the taxonomic distribution to search results. It might be due to naming of the javascript objects (extra_seq_parameters_PAGENAME?)
