### ISSUE TITLE
H1 seeds has to be fixed

### ISSUE THREAD

**Issue by molsim** [edraizen/HistoneDB#61]
While I will work on refining the H1 seeds at some point,
currently, several seeds has the same sequence, which results in an error during "manage.py buildvariants".
Here is the problem:
H1.8.fasta:>Mus|19923865|H1.8 Mus_H1oo
H1.8_0.fasta:>Mus|19923865|H1.8 Mus_H1oo
H1.8_0_0.fasta:>Mus|19923865|H1.8 Mus_H1oo

**Comment by edraizen** [comment]
Yes, this seems to be a problem when I "clean up" the files after building the pdfs, and then rerunning any of the build commands the need unique seed sequences.
