### ISSUE TITLE
Suggested enhancement to the curated seqs view, as discussed with Anya

### ISSUE THREAD

**Issue by molsim** [edraizen/HistoneDB#62]
Here is an enhancement idea, we discussed with Anya, to be applied to Curated sequences MSA view.
1) Delete the LOGO plot.
2) make two lines for feature annotations:
1. secondary structure elements. Possible ones are: alpha1, alpha2, alpha3. alphaC, alphaN, beta1,beta2,beta3, betaC?
2. structural features: L1, L2, docking domain, macro domain.
3) Functional features to be highlighted in color: key ARG, acidic patch, modified residues
Place a legend to the left of the MSA viewer explaining the color coding.

**Comment by edraizen** [comment]
1) Done
2) All of the secondary structures you mentioned should be in there. We are currently using the features you previously identified and their positions in the canonical to match the position in a new sequence using needle:

``` 
ss_templ_H3 = {
    'alphaN':[43,56],
    'alpha1':[62,76],
    'alpha2':[84,113],
    'alpha3':[119,130],
    'loopL1':[78,83],
    'loopL2':[114,118],
    'beta1':[82,83],
    'beta2':[117,118],
    'mgarg1':[62,62],
    'mgarg2':[82,82],
    'mgarg3':[48,48]
}
ss_templ_H4 = {
    'alpha1ext':[23,28],
    'alpha1':[29,40],
    'alpha2':[48,75],
    'alpha3':[81,92],
    'loopL1':[41,47],
    'loopL2':[76,81],
    'beta1':[44,45],
    'beta2':[79,80],
    'beta3':[95,97],
    'mgarg1':[44,44]
}

#new def of docking domains as in Suto Luger 2000
ss_templ_H2A = {
    'alpha1ext':[15,21],
    'alpha1':[25,36],
    'alpha2':[45,72],
    'alpha3':[78,88],
    'alpha3ext':[89,96],
    'loopL1':[37,44],
    'loopL2':[73,77],
    'beta1':[41,42],
    'beta2':[76,77],
    'beta3':[99,101],
    'docking domain':[80,118],
    'mgarg1':[41,41],
    'mgarg2':[76,76]
}

ss_templ_H2B = {
    'alpha1':[33,45],
    'alpha2':[51,80],
    'alpha3':[86,98],
    'alphaC':[99,119],
    'loopL1':[46,50],
    'loopL2':[81,85],
    'beta1':[49,50],
    'beta2':[84,85],
    'mgarg1':[29,29]
}
```
3) We can functional features in color. The one problem is that we are aligning to canonical, not the variant, but that can change. key ARG is done, but we can add acidic patch, modified residues. Do you have a list of positions?

**Comment by molsimmsu** [comment]
1) LOGO is still there
2) ok.
3) I'll work on that.

**Comment by edraizen** [comment]
Features have been added for most, so closing this issue
