### ISSUE TITLE
GIs link to NCBI

### ISSUE THREAD

**Issue by molsim** [edraizen/HistoneDB#64]
Leonardo suggested to make GI numbers as links to NCBI pages.

**Comment by edraizen** [comment]
Would another arrow next to the GI, with an option to view in Entrez suffice? If you select one ore more and click export->View in Entrez, it will do what you want.

**Comment by anna-panchenko** [comment]
I don't think it is a priority, we can add these links later.

Sent from my iPhone

On Aug 7, 2015, at 12:56 PM, edraizen <notifications@github.com<mailto:notifications@github.com>> wrote:


Would another arrow next to the GI, with an option to view in Entrez suffice? If you select one ore more and click export->View in Entrez, it will do what you want.
