### ISSUE TITLE
Active sequence select on Curated seqs tab.

### ISSUE THREAD

**Issue by molsim** [edraizen/HistoneDB#70]
Hi Eli,
can you point me to how to revert back the behavior when clicking anywhere on the row in the table triggered the update of the MSA on top?

I nice option would be also to highlight the selected row with color.
Alex

**Comment by edraizen** [comment]
The relevant code can be found when in bootsrap-table's events [onLoadSuccess and onCheck](https://github.com/edraizen/HistoneDB/blob/master/templates/test.html#L278-L285).

To add color, you need to use a rowStyle or cellStyle formatter function. See http://bootstrap-table.wenzhixin.net.cn/documentation/

**Comment by molsim** [comment]
Thanks a lot, done.
