### ISSUE TITLE
 quick way to see all variants of one species

### ISSUE THREAD

**Issue by molsim** [edraizen/HistoneDB#77]
We are currently lacking an easy way to view all H2A variants of human in one alignment, and so on.
Going to H2A page and filtering by Homo returns unexpectedly all variants.

**Comment by edraizen** [comment]
Does that help? or do you think thee needs to be amore prominent button?

**Comment by molsim** [comment]
Yes, I think this helps.
Only probably "View ... for ...." . Since we only have species there, not higher taxons?
Is the search bug also fixed?
