### ISSUE TITLE
View variant within taxonomy

### ISSUE THREAD

**Issue by molsim** [edraizen/HistoneDB#82]
What does this really mean and why we need it?

**Comment by edraizen** [comment]
It is supposed to mean "exlore sequences from this variant that have this taxon taxonomy"

**Comment by molsim** [comment]
it might be good to view all H2As from human, let say.
but then it should say "View histones of same type for this species"
or "View same variants for this species"
anyway we have only taxonomic leaves, correct?

**Comment by edraizen** [comment]
Yes, all sequences point to a taxonomy of species, which are leaves. But they all have parent and parents attributes and can be linked together.
